clean:
	rm q1 q2 q3 q4 q5 q6 q7 q8 q9 q10

q1:
	g++ q1.cpp -o q1

q2:
	g++ q2.cpp -o q2

q3:
	g++ q3.cpp -o q3

q4:
	g++ q4.cpp -o q4

q5:
	g++ q5.cpp -o q5

q6:
	g++ q6.cpp -o q6

q7:
	g++ q7.cpp -o q7

q8:
	g++ q8.cpp -o q8

q9:
	g++ q9.cpp -o q9
